### ISSUE TITLE
getting no module 'src' while running python van.py 

### ISSUE THREAD

**Issue by girmax** [ClimenteA/pyvan#6]
here is the error message:

```
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\max\onedrive main\python_projects\flask_projects\dist\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\max\\AppData\\Local\\Temp\\pip-install-r33u
x_a5\\future\\setup.py'"'"'; __file__='"'"'C:\\Users\\max\\AppData\\Local\\Temp\\pip-install-r33ux_a5\\future\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r
\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\max\AppData\Local\Temp\pip-install-r33ux_a5\future\pip-egg-info'
         cwd: C:\Users\max\AppData\Local\Temp\pip-install-r33ux_a5\future\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\max\AppData\Local\Temp\pip-install-r33ux_a5\future\setup.py", line 86, in <module>
        import src.future
    ModuleNotFoundError: No module named 'src'

```

**Comment by ClimenteA** [comment]
pyvan has some issues detecting all modules needed for the script to run..

To debug pyvan: 
- Enter in the `dist` folder there you have the embeded version of python with the scripts you wrote.
- try to run your script file from there `python myscript.py` and see where it fails (most probably at installing additional modules)
- then install them manually go in the `dist/Scripts` folder (there you have pip.exe) and install the modules needed to run the script

Can you provide a link to your github repo to test it on my side and see if I can fix it?

**Comment by ClimenteA** [comment]
upgrade to 0.0.5 version and see if it fails
